config/routes.rb
Rails.application.routes.draw do
  # Here we created nested routes to create students in context of the teacher
  resources :teachers do
    resources :students
  end
  # Other routes go here
  root "teachers#index"
  get "up" => "rails/health#show", as: :rails_health_check

 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :teacher
end

app/models/teacher.rb
class Teacher < ApplicationRecord
has_many :students, dependent: :destroy, inverse_of: :teacher
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_teacher
  before_action :set_student, only: [:edit, :update, :show, :destroy]

  # GET /students or /students.json
  def index
    @student = Student.all
  end

  # GET /students/1 or /students/1.json
  def show
    @student = Student.all
  end

  # GET /students/new
  #Modified to add teacher's id
  def new
    @student = @teacher.students.build
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students or /students.json
  #Modified to add teacher's id
  def create
    @student = @teacher.students.build(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to teacher_url(@teacher), notice: "Student was successfully created." }
        format.json { render :show, status: :created, location: @teacher }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1 or /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @teacher, notice: "Student was successfully updated." }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1 or /students/1.json
  def destroy
    @student.destroy!

    respond_to do |format|
      format.html { redirect_to teacher_student_url(@teacher), notice: "Student was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_student
    @student = Student.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def student_params
    params.require(:student).permit(:name, :gender, :grade, :attended, :teacher_id)
  end

  # Created to find the teacher's id and pass it through the before_action event
  def set_teacher
    @teacher = Teacher.find(params[:teacher_id])
  end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :set_teacher, only: %i[ show edit update destroy ]

  # GET /teachers or /teachers.json
  def index
    @teachers = Teacher.all
  end

  # GET /teachers/1 or /teachers/1.json
  def show
  end

  # GET /teachers/new
  def new
    @teacher = Teacher.new
  end

  # GET /teachers/1/edit
  def edit
  end

  # POST /teachers or /teachers.json
  def create
    @teacher = Teacher.new(teacher_params)

    respond_to do |format|
      if @teacher.save
        format.html { redirect_to teacher_url(@teacher), notice: "Teacher was successfully created." }
        format.json { render :show, status: :created, location: @teacher }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teachers/1 or /teachers/1.json
  def update
    respond_to do |format|
      if @teacher.update(teacher_params)
        format.html { redirect_to teacher_url(@teacher), notice: "Teacher was successfully updated." }
        format.json { render :show, status: :ok, location: @teacher }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teachers/1 or /teachers/1.json
  def destroy
    @teacher.destroy!

    respond_to do |format|
      format.html { redirect_to teachers_url, notice: "Teacher was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teacher
      @teacher = Teacher.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    # Added students_attributes
    def teacher_params
      params.require(:teacher).permit(:name, :age, :visited, students_attributes: [:id, :name, :gender, :grade, :_destroy])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Schooldata</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/students/_form.html.erb
<%= form_with(model: @student) do |form| %>
  <% if student.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
        <% student.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_area :name %>
  </div>

  <div>
    <%= form.label :gender, style: "display: block" %>
    <%= form.text_area :gender %>
  </div>

  <div>
    <%= form.label :grade, style: "display: block" %>
    <%= form.text_area :grade %>
  </div>

  <div>
    <%= form.label :attended, style: "display: block" %>
    <%= form.check_box :attended %>
  </div>

  <div>
    <%= form.label :teacher_id, style: "display: block" %>
    <%= form.text_field :teacher_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/students/_student.html.erb
<div id="<%= dom_id student %>">
  <p>
    <strong>Name:</strong>
    <%= student.name %>
  </p>

  <p>
    <strong>Gender:</strong>
    <%= student.gender %>
  </p>

  <p>
    <strong>Grade:</strong>
    <%= student.grade %>
  </p>

  <p>
    <strong>Attended:</strong>
    <%= student.attended %>
  </p>

  <p>
    <strong>Teacher:</strong>
    <%= student.teacher_id %>
  </p>

</div>

app/views/students/edit.html.erb
<%= form_with(model: [@teacher, @student]) do |form| %>

  <h1>Editing student</h1>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :gender %>
    <%= form.text_field :gender %>
  </div>

  <div>
    <%= form.label :grade %>
    <%= form.text_field :grade %>
  </div>

  <div class="field">
  <%= form.label :attended %>
  <%= form.text_field :attended %>
  </div>

  <div>
    <%= form.submit "Update Student" %>
  </div>
<% end %>

<div>
  <% # link_to "Show this student", teacher_student_path(@teacher, @student) %> 
  <%= link_to "Back to students", @teacher %>
</div>

app/views/students/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Students</h1>

<div id="students">
  <% @students.each do |student| %>
    <%= render student %>
    <p>
      <%= link_to "Show this student", student %>
    </p>
  <% end %>
</div>

<%= link_to "New student", new_student_path %>

app/views/students/new.html.erb
<!-- app/views/students/new.html.erb -->
<h1>New Student for <%= @teacher.name %></h1>

<%= form_with(model: [@teacher, @student], local: true) do |form| %>
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
        <% @student.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :grade %>
    <%= form.text_field :grade %>
  </div>

  <div class="field">
    <%= form.label :gender %>
    <%= form.text_field :gender %>
  </div>

  <div class="field">
    <%= form.label :attended %>
    <%= form.text_field :attended %>
  </div>

  </div>

  <!-- Add other student fields as needed -->

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/students/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @student %>

<div>
  <%= link_to "Edit this student", edit_teacher_student_path(@student) %> |
  <%= link_to "Back to students", teacher_students_path %>
</div>

app/views/teachers/_form.html.erb
<%= form_with(model: teacher) do |form| %>
  <% if teacher.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(teacher.errors.count, "error") %> prohibited this teacher from being saved:</h2>

      <ul>
        <% teacher.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_area :name %>
  </div>

  <div>
    <%= form.label :age, style: "display: block" %>
    <%= form.text_area :age %>
  </div>

  <div>
    <%= form.label :visited, style: "display: block" %>
    <%= form.check_box :visited %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/teachers/_teacher.html.erb
<div id="<%= dom_id teacher %>">

<table>
  <tr>
    <th>Teacher's Name</th>
    <th>Age</th>
    <th>Visited</th>
  </tr>
  
  <tr>
    <td><%= teacher.name %></td>
    <td><%= teacher.age %></td>
    <td><%= teacher.visited %></td>
  </tr>

  </table>

app/views/teachers/edit.html.erb
<h1>Editing teacher</h1>

<%= render "form", teacher: @teacher %>

<br>

<div>
  <%= link_to "Show this teacher", @teacher %> |
  <%= link_to "Back to teachers", teachers_path %>
</div>

app/views/teachers/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Teachers Home</h1>


<table>
  <tr>
  <th>Teacher's Name</th>
  <th>Age</th>
  <th>Visited</th>
  <th>Actions</th>
  </tr>
  
  <% # * The next ruby code encapsulates the <tr> </tr> content to repeat those rows for each student entries %>
  <% @teachers.each do |teacher| %>
  <tr>
  <td><%= teacher.name %></td>
  <td><%= teacher.age %></td>
  <td><%= teacher.visited %></td>
  <td><%= link_to "Show this teacher", teacher %></td>
  </tr>
  <% end %>
  </table>



<%= link_to "New teacher", new_teacher_path %>

app/views/teachers/new.html.erb
<h1>New teacher</h1>

<%= render "form", teacher: @teacher %>

<br>




<div>
  <%= link_to "Back to teachers", teachers_path %>
</div>

app/views/teachers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @teacher %>

<div>
  <%= link_to "Edit this teacher", edit_teacher_path(@teacher) %> |
  <%= link_to "Back to teachers", teachers_path %>

  <%= button_to "Destroy this teacher", @teacher, method: :delete %>
</div>

</br></br></br>


<h1>Teacher's Name: <%= @teacher.name %></h1>
<h5> Teacher-associated student names go here: </h5>
<p><%= link_to 'Add Student', new_teacher_student_path(@teacher) %></p>

<h2>Added Students</h2>

  
  <table>
  <tr>
    <th>Student Name</th>
    <th>Gender</th>
    <th>Grade</th>
    <th>Attended</th>
    <th>Actions</th>
  </tr>
  
  <%# * The next ruby code encapsulates the <tr> </tr> content to repeat those rows for each student entries  %>
  <% @teacher.students.each do |student| %>
  <tr>
    <td><%= student.name %></td>
    <td><%= student.gender %></td>
    <td><%= student.grade %></td>
    <td><%= student.attended %></td>
    <td><%= link_to "Edit", edit_teacher_student_path(@teacher, student) %> </td>
  </tr>
  <% end %>
  </table>
  